### ISSUE TITLE
Villageois

### ISSUE THREAD

**Issue by PapyConfig** [Breakerland/Breakerland-Survie#11]
Plusieurs problèmes liés aux Villageois : 
 - Ne se reproduisent plus
 - Ne font plus de réduction aux joueurs, même avec Héros du Village
 - Ne se transforment plus en Zombie Villageois (à vérifier)

P.S : J'enlève Villageois du précédent Issue

**Comment by PapyConfig** [comment]
Pour répondre à ta question Coco, peu importe le nombre de Villageois dans un chunk, la reproduction ne marche pas

**Comment by Gwan-Forth** [comment]
Tous les pré-requis sont fait pour la reproduction ?

Il faut qu'il y en ait 2 au minimum, que tu les nourrissent en leurs envoyant de la nourriture (carrots et je sais plus quoi encore), et qu'il y ait des lits.

**Comment by Corenb** [comment]
C'est normalement corrigé (à vérifier ?)
