### ISSUE TITLE
Plus aucun dégâts des phantoms et withers 

### ISSUE THREAD

**Issue by PapyConfig** [Breakerland/Breakerland-Survie#8]
Les phantoms ne font plus de dégâts aux joueurs.
Les withers ne peuvent être summon que dans des claims et ne font pas de dégâts (ni explosion, ni l'effet wither)
Les creepers ne font pas de dégâts aux joueurs lorsqu'ils explosent dans un claim.
Normal ou bug ?

**Comment by PapyConfig** [comment]
Les phantoms ne font pas de dégâts à l'intérieur des claims mais en font à l'extérieur

**Comment by Corenb** [comment]
@PapyGamer c'est réglé non?

**Comment by PapyConfig** [comment]
Non toujours pas
