### ISSUE TITLE
Moutons, Random tick speed

### ISSUE THREAD

**Issue by PapyConfig** [Breakerland/Breakerland-Survie#9]
Les moutons ne broutent plus.
Le random tick speed est pas mal bas.

**Comment by Corenb** [comment]
Ouvre moi la prochaine fois 1 ticket / problème.

Pour les villageois, a partir de combien dans la même zone la reproduction ne fonctionne plus?

**Comment by Gwan-Forth** [comment]
De ce que j'ai trouvé sur le wiki officiel : 

> **Grazing**
> Sheep eat grass blocks, changing them into dirt blocks. When a sheared sheep eats a grass block during the daytime, its wool grows back. Therefore, if no grass is available, a sheep cannot regrow its wool after being sheared. They can't eat a grass block with tall grass on it but can eat the tall grass, making it disappear. If an adult sheep has the opportunity, the chance of eating grass is 1⁄1000 per game tick (1⁄50 for lamb).

je n'ai pas trouvé avec spigot de configuration des ticks pour les sheep. Du coup ce n'est pas possible de modifier ça sans possiblement passer par un plugin s'il y en a un.

j'ai fait des tests et les moutons broutent bien pour moi. Par contre ils ne transforment pas l'herbe en terre, mais je pense pas que ce soit problématique si ?

**Comment by PapyConfig** [comment]
Effectivement le problème des moutons qui ne broutent plus est réglé mais comme tu l'as dis le block de grass n'est plus changé en dirt, ce qui fait que les usines à laine ne fonctionne plus, car elle regarde si le block de grass change d'état

**Comment by Gwan-Forth** [comment]
Trouvé ailleurs : 

> If you have mob griefing turned off sheep do not need to eat grass / turn it to dirt, villagers do not pick up items and creeper explosions do not damage buildings.

De mémoire je crois qu'il est activé pour éviter les soucis avec les creeper, et du coup ça impact les moutons aussi.

A choisir entre les fermes à mouton et les trous des creepers ^^

**Comment by Corenb** [comment]
C'est possible qu'il soit activé mais dû a un précèdent bug, sinon il faut vérifier dans les options du terrain que le mob griefing est activé

**Comment by PapyConfig** [comment]
Okay, je testerai ce soir alors
